### ISSUE TITLE
How to show a word meaning as a document?

### ISSUE THREAD

**Issue by ivan-volnov** [uga-rosa/cmp-dictionary#44]
Hi!

Thanks for the great plugin!

I use it with my [anki](https://apps.ankiweb.net/) word deck to use the vocabulary I'm learning. Extremely useful!

Please add LSP preview what can display a word meaning or translation.

![image](https://user-images.githubusercontent.com/51086293/232215965-b8f8de88-f15c-41b2-86f5-9c838f8ac521.png)

**Comment by ivan-volnov** [comment]
Just a plain text.
The dict format could be:
```
word1 meaning1
word2 meaning2
...
```
Or something another..

**Comment by uga-rosa** [comment]
Hi. Thanks for using this plugin.
I can't support that grammar, sorry. Because I want to keep the dictionary format compatible with the 'dictionary' option (That is, in the form of a collection of words separated by spaces, line breaks, and other whitespace characters).
But there is a way. See `:h cmp-dictionary-document`. Documentation can be attached using a program such as wordnet where you can get a description of the word from the word.
![image](https://user-images.githubusercontent.com/82267684/232228922-16a925d3-600e-4bf2-bc35-42f7cb690f7b.png)

If you want to add your own description, create a program like this one.
```lua
local dictionary = {
  word1 = "meaning1",
  word2 = "meaning2",
}

local word = arg[1]
if word then
  print(dictionary[word])
end
```

**Comment by ivan-volnov** [comment]
Thanks for the reply!

Well, can you make document_command accept a lua function optionally without an external tool? A system command call is quite slow.

Or may be better add an alternative way we can inject words and "documentation" as a lua dict instead of a dict file and a separate call to document_command? So user can implement their own format and parsers.

And how to hide "belong to" record?

**Comment by uga-rosa** [comment]
It is true that external commands are slow, but I think this is not a practical problem since it is delayed until the candidate is selected. This feature originally came about because of requests to use wordnet.

You can create your own sources, so if you want to pass tables from lua, it is better to do so.
```lua
require('cmp').setup({
  ...
  sources = {
    ...
    { name = 'meaning' },
  },
})

local meaning = {}

function meaning:is_available()
  return true
end

function meaning:get_debug_name()
  return 'debug name'
end

function meaning:get_keyword_pattern()
  return [[\k\+]]
end

function meaning:get_trigger_characters()
  return { '.' }
end

function meaning:complete(params, callback)
  callback({
    { label = 'word1', documentation = 'meaning1' },
    { label = 'word2', documentation = 'meaning2' },
  })
end

function meaning:resolve(completion_item, callback)
  callback(completion_item)
end

function meaning:execute(completion_item, callback)
  callback(completion_item)
end

require('cmp').register_source('meaning', meaning)
```

Currently, it is not possible to set the `belong to` to be hidden. I will add the option.

**Comment by ivan-volnov** [comment]
Thanks a lot! Tested. It works.

**Comment by uga-rosa** [comment]
Good. Can you close this issue?
